# Generated by Django 5.2.10 on 2026-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='about/')),
                ('video', models.URLField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
