# Generated by Django 5.2.10 on 2026-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
