# Generated by Django 5.2.10 on 2026-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_about_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
