# Generated by Django 5.2.10 on 2026-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_mission_about_value_about_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bg_photo',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
