# Generated by Django 5.2.10 on 2026-01-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
