# Generated by Django 5.2.10 on 2026-01-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactus_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='webite',
            new_name='website',
        ),
    ]
