# Generated by Django 5.2.10 on 2026-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
