# Generated by Django 5.2.10 on 2026-01-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_contact_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Readit.', max_length=120)),
                ('logo_text', models.CharField(default='Readit.', max_length=120)),
                ('footer_about', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='home.sitesettings')),
            ],
        ),
    ]
